// WARNING:
// This file is generated by a grunt build task.
// Do not modify it by hand.

/**
 * Messages from `geoenrichment/t9n/DataBrowser/DataBrowser_en.json`.
 */
export default interface DataBrowserMessages {
  VariableStore: {
    number: string;
    percent: string;
    average: string;
    index: string;
    reliability: string;
  };
  CountrySelect: {
    global: string;
    allHierarchies: string;
  };
  DataCategoriesPage: {
    loading: string;
    search: string;
    noResults: string;
    showFavorites: string;
  };
  DataCollectionsPage: {
    categoryName: string;
    mapPopVar: string;
    keepBrowse: string;
    showAll: string;
    noResults: string;
    search: string;
  };
  DataVariablesPage: {
    allVariablesTitle: string;
    favoriteVariablesTitle: string;
    groupVariables: string;
    searchVariables: string;
    allVariables: string;
    searchInGroupVariables: string;
    favoriteVariables: string;
    customSearch: string;
  };
  ShoppingCart: {
    selectedVars: string;
    noVariables: string;
    editVariable: string;
    replaceVariable: string;
    removeVariable: string;
  };
  VariableInfo: {
    name: string;
    variable: string;
    source: string;
    vintage: string;
    percentBase: string;
    averageBase: string;
    indexBase: string;
    filters: string;
    definition: string;
  };
  WizardButtons: {
    back: string;
    apply: string;
    cancel: string;
    next: string;
  };
  DataBrowser: {
    title: string;
  };
}
