// WARNING:
// This file is generated by a grunt build task.
// Do not modify it by hand.

/**
 * Messages from `geoenrichment/t9n/infographics/infographics_en.json`.
 */
export default interface InfographicsMessages {
  bufferTitle: {
    pointRing: {
      esriFeet: string;
      esriKilometers: string;
      esriMeters: string;
      esriMiles: string;
    };
    pointDriveTime: {
      esriFeet: string;
      esriKilometers: string;
      esriMeters: string;
      esriMiles: string;
      esriDriveTimeUnitsMinutes: string;
    };
    lineBuffer: {
      esriFeet: string;
      esriKilometers: string;
      esriMeters: string;
      esriMiles: string;
    };
    polygon: string;
    stdGeo: string;
  };
  AgePyramid: {
    maxLabel: string;
    minLabel: string;
    compLabel: string;
    menLabel: string;
    womenLabel: string;
  };
  OneVar: {
    subtitleSite2: string;
    subtitleVar2: string;
    lessThan: string;
    moreThan: string;
    same: string;
    areaCol: string;
    valueCol: string;
  };
  RelatedVariables: {
    highLabel2: string;
    lowLabel2: string;
    indicatorCol: string;
    valueCol: string;
    difCol: string;
    chartLabel: string;
  };
  Tapestry: {
    hhTypeLabel: string;
    medianAgeLabel: string;
    incomeLabel: string;
    employmentLabel: string;
    educationLabel: string;
    residentialLabel: string;
    raceEthnicityLabel: string;
    hhLabel: string;
    adultsLabel: string;
    prtHhLabel: string;
    viewFullSegmentProfile: string;
    noSegmentsFound: string;
  };
  Prizm5: {
    hhLabel: string;
    prtHhLabel: string;
    hhIncome: string;
    lifeStage: string;
    urbanity: string;
    viewFullSegmentProfile: string;
    noSegmentsFound: string;
  };
}
