// WARNING:
// This file is generated by a grunt build task.
// Do not modify it by hand.

/**
 * Messages from `geoenrichment/t9n/widgets/widgets_en.json`.
 */
export default interface WidgetsMessages {
  ImageNavigator: {
    paginationLabel: string;
    noImage: string;
    previewNotAvailable: string;
  };
  PageNavigator: {
    currentPageOutOfN: string;
  };
  PanoramicViewer: {
    "image-viewer-close": string;
    "image-viewer-fullscreen": string;
    "image-viewer-minimize": string;
    "image-viewer-title": string;
    "image-viewer-show-caption": string;
    "image-viewer-hide-caption": string;
  };
  TextBox: {
    error_numberExpected: string;
    error_range: string;
  };
}
